### ISSUE TITLE
Can this library be used to create a custom badge for the tab bar? 

### ISSUE THREAD

**Issue by goelv** [ckteebe/CustomBadge#14]

**Comment by preetamjadakar** [comment]
@ckteebe : I have tried it, able to add in tabbar controller but after a while unable to change the badge value.
Even when I NSLog badgeLabel, 
appDelegate.myTabbarController.badgeNotification.badgeText;

its showing expected value, but its not reflecting in tab bar controller.

Can you please suggest something.

Thanks!
